services:
  - type: web
    name: arbitrage-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard_app.py --server.port=$PORT --server.address=0.0.0.0
